{% set name = "pipreqs" %}
{% set version = "0.5.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/bndr/{{ name }}/archive/refs/tags/v{{ version }}.tar.gz
  sha256: aee67b99063504941259421ca84ff0350c3b9516c880db5b52dd86fa676a72f1
  patches:
    - patches/0001-update-dependencies.patch

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  entry_points:
    - pipreqs=pipreqs.pipreqs:main
  skip: True  # [py<38 or py>312]

requirements:
  build:
    - patch # [not win]
    - m2-patch # [win]
  host:
    - pip
    - python
    - poetry-core
  run:
    - python
    - yarg >=0.1.9
    - docopt >=0.6.2
    - nbconvert >=7.11.0,<8.0.0
    - ipython >=8.12.3
  run_constrained:
    - python >=3.8.1

# assert os.path.getsize(notebook_requirement_path) == 1
# AssertionError: assert 2 == 1
{% set tests_to_skip = "test_ignore_notebooks" %}

test:
  source_files:
    - tests
  imports:
    - pipreqs
  commands:
    - pip check
    - pipreqs --help
    - python -c "from importlib.metadata import version; assert(version('{{ name }}')=='{{ version }}')"
    - pytest -v -k "not {{ tests_to_skip }}" tests
  requires:
    - pytest
    - pip

about:
  home: https://github.com/bndr/pipreqs
  summary: Pip requirements.txt generator based on imports in project
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  description: Generate requirements.txt file for any project based on imports
  dev_url: https://github.com/bndr/pipreqs
  doc_url: https://github.com/bndr/pipreqs/blob/master/README.rst

extra:
  recipe-maintainers:
    - proinsias
    - ericmjl