travis:
  secure:
    BINSTAR_TOKEN: WJ0ptW+zepu4lw+3dq9B3oapmtwx91F6NeiuXRDLZycTZUbH8CJY+x0A/WctgAwqyYvdSywaOPtMvW9WWNDd11/fHfxkOWiJMKfHBUt63GlD+2WM/scSGmVpu58LaOWHEljg7p19x42yMuDhWgOrFhfrHQgFvfosXPSIuc1iwmYtePRimNuyUGPNRujGqmKqFk6zUY0y7DISyHV2fuGi0kqfCMFtbXOckaApSpbiSZCdTbHEQe9jg5ItnESeWYmliEYOI3l9tXSRidTsq7FjUJSP170RpI0gPC4PFA/r3sikMij2uV4XFr8qKi5GA5ulkcCo8fbc7dH40RSwxiYR/M96TOLkv63Pv20j9qaDkXL16EogU/i9Pha8pKcxiWeQLnchL1JJdznCZdBobGIeLBVQVrI3yuSGDlamUJrDoqebT7rkFSs42LhTx98h1j+L8GFzXl1Tk82fxDixCKOHxUQwKtOWoIzBhyqT1rwaEGy2KXNcSKgQ+jmt30xBTOI5qXABUnoTQNaIvyNfF/a/pw7VW9ZYR/8a0C7vzAaNWTESP8UBuPiuwJq2uAxsRRpMVlQZ/kxtB9UlQYOTt3aMsy4QKZP1ts90dsQ9vXhyJPFgwgUUeCr/1eFsuAPhfTec0moo75nG9V4ufcJ/0UGZLRC8yTVt8ZQ4PsDHPaaWOFc=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
