travis:
  secure:
    BINSTAR_TOKEN: lPJtIhegaLdtigNLtPZ8XUUAvmNbkeWQJLps6uvsEUK7x5DWjF9raTztsDY+pNJxiI6cu8Ne9RBNOMiMzpaIsI7VOh5h74borxftzOzmcbxAGGhRExMF4BS6wLILlqMCcceTqNwR0WwyCrzr4HiHssQB3KTnJV6bvLiodUUVHrPPhnzmSPaY5j4VkEHs1ZEQNhi/6xPSTA3Ft8nmnqEHpANPWbeQYqIKmycZASrIPjrAEem/ssRDA0B+Lt0T239UVXkdfDEei5HL8ALNEMyAyzQHWdw4voIAuGiPv3DSSoQHIMTaHdtdNl8CDjm/0K2WeBSaQfgqXPuDZzRVvJmBByAaS78QeXIJvTWX6ACsGVtmBLippHOPG55bqencRyGni5HmulQLOabKsiL31h0mc+f5w/GTPH8qpixWg49hp3CZYrRonqv4zIXsu4JT/0S5GD6fmQXONGG3bjgC77RGBmjr8ItJ56pvcET6oFhLvrWYGC0KbxZJeNDEwzRmdv7SwzM9NWSTT9tQIsBbsjnd4d3kQSkjs4jeH19scNjwhmpFWtL3yt9x1z2f7vF3gfFam2TF0RHYS216djYixtQtEI7hogAOrWzVrq4elqbsZd2XyNRoapP7qb9nHeOd0rPvY5dA+BuaH1HlGkKytpzi6+5GUOtEWHcMitzIfoLza6I=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
bot:
  automerge: true
